### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by ajmueller** [tumblr/gulp-css-hashes#1]
The documentation says `assetPath` is an option, but it should be `assetsPath`.  I would submit a PR for this, but submitting the CLA for something so small seemed silly.

**Comment by heylookltsme** [comment]
Thank you for pointing that out @ajmueller! 

Hey, @shahkashani is this something you guys could take care of? I'd do it myself, but I'm now subject to the same CLA situation. 😿

**Comment by shahkashani** [comment]
Sorry for the absolutely comical delay on this, there's a fix coming soon: https://github.com/tumblr/gulp-css-hashes/pull/2/

**Comment by fabianmarz** [comment]
Just stumbled across this and wanted to let you know, the package needs an update on [`npmjs.com`](https://www.npmjs.com/package/gulp-css-hashes) as well. The docs there still state `assetPath` instead of `assetsPath`.
